<font size="-1"><b><a href="freelex">Home</a> &bull; 
<a href="headword/display?_id=new">Add</a> &bull; 
<a href="headword/myediting">My Editing</a> &bull; 
<a href="search">Search</a> &bull; 
[% IF c.controller('corpus') != '' %]<a href="corpus">Corpus</a> &bull; [% END %]
<a href="reports/sql">Reports</a> &bull; 
<a href="print/detail">Print</a> &bull; 
<a href="logout">Logout</a></b></font><br>
